<?php

/**
 * @file
 * Contains farm_equipment.module.
 */

declare(strict_types=1);

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_base_field_info().
 */
function farm_equipment_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];

  // Add an Equipment reference field to logs.
  if ($entity_type->id() == 'log') {
    $options = [
      'type' => 'entity_reference',
      'label' => t('Equipment used'),
      'description' => t('What equipment was used?'),
      'target_type' => 'asset',
      'target_bundle' => 'equipment',
      'multiple' => TRUE,
      'weight' => [
        'form' => 40,
        'view' => 40,
      ],
    ];
    $fields['equipment'] = \Drupal::service('farm_field.factory')->baseFieldDefinition($options);
  }

  return $fields;
}

/**
 * Implements hook_farm_import_csv_base_fields().
 */
function farm_equipment_farm_import_csv_base_fields(string $entity_type) {
  $base_fields = [];

  // Add equipment base field to log CSV importers.
  if ($entity_type == 'log') {
    $base_fields[] = 'equipment';
  }

  return $base_fields;
}

/**
 * Implements hook_farm_ui_views_base_fields().
 */
function farm_equipment_farm_ui_views_base_fields(string $entity_type) {
  $base_fields = [];

  // Add equipment base field to farmOS log Views.
  if ($entity_type == 'log') {
    $base_fields[] = 'equipment';
  }

  return $base_fields;
}

/**
 * Implements hook_farm_ui_theme_field_group_items().
 */
function farm_equipment_farm_ui_theme_field_group_items(string $entity_type, string $bundle) {
  if ($entity_type == 'log') {
    return [
      'equipment' => 'asset',
    ];
  }
  return [];
}
